package artisan

const (
	TagAlias            = "alias"
	TagDesc             = "desc"
	TagType             = "type"
	TagDefault          = "default"
	TagHasValue         = "hasValue"
	TagRequired         = "required"
	TagArray            = "array"
	TagValueArg         = "arg"
	TagValueOpt         = "opt"
	fieldTypeString     = "string"
	fieldTypeBool       = "bool"
	fieldTypeFloat64    = "float64"
	fieldTypeFloat32    = "float32"
	fieldTypeInt64      = "int64"
	fieldTypeUInt64     = "uint64"
	fieldTypeInt32      = "int32"
	fieldTypeUInt32     = "uint32"
	fieldTypeInt        = "int"
	fieldTypeUInt       = "uint"
	fieldTypeStringPtr  = "*string"
	fieldTypeBoolPtr    = "*bool"
	fieldTypeFloat64Ptr = "*float64"
	fieldTypeFloat32Ptr = "*float32"
	fieldTypeInt64Ptr   = "*int64"
	fieldTypeInt32Ptr   = "*int32"
	fieldTypeIntPtr     = "*int"
	fieldTypeUInt64Ptr  = "*uint64"
	fieldTypeUInt32Ptr  = "*uint32"
	fieldTypeUIntPtr    = "*uint"
)
